use std::{collections::HashMap, fs, path::PathBuf};

use anyhow::{bail, Context, Result};
use lsb_scrape::{check_scrape_count, parse_yaml, parse_yaml_enum_values, zone_data_files, Yaml};

const LSB_ZONE_ENUM_YAML: &str = "../vendor/server/data/enums/zone.yaml";
const LSB_ZONES_DATA_DIR: &str = "../vendor/server/data/zones";

/// Smallest row count each scrape can return and still plausibly have parsed
/// the zone files; the argument is the count the pinned vendor tree yields
/// today (kuluu-m4yk).
mod floor {
    use lsb_scrape::scrape_floor;

    pub const ZONE_LINE: usize = scrape_floor(844);
    pub const FROM_ZONE: usize = scrape_floor(198);
}

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={LSB_ZONE_ENUM_YAML}");
    println!("cargo:rerun-if-changed={LSB_ZONES_DATA_DIR}");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").context("OUT_DIR not set")?);

    let zone_src = fs::read_to_string(LSB_ZONE_ENUM_YAML)
        .with_context(|| format!("reading {LSB_ZONE_ENUM_YAML}"))?;
    let zone_ids: HashMap<String, u16> = parse_yaml_enum_values(&zone_src)
        .with_context(|| format!("parsing {LSB_ZONE_ENUM_YAML}"))?
        .into_iter()
        .map(|(name, id)| {
            u16::try_from(id)
                .map(|id| (name, id))
                .with_context(|| format!("zone id {id} overflows u16"))
        })
        .collect::<Result<_>>()?;
    let mut entries = parse_zonelines(&zone_ids)?;

    entries.sort_by_key(|z| (z.from_zone, z.line_id));

    let mut index: Vec<(u16, u32, u32)> = Vec::new();
    let mut i = 0u32;
    while (i as usize) < entries.len() {
        let zone = entries[i as usize].from_zone;
        let start = i;
        while (i as usize) < entries.len() && entries[i as usize].from_zone == zone {
            i += 1;
        }
        index.push((zone, start, i));
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by kuluu-nav/build.rs from data/zones/<zone>/zone.yaml.\n");
    out.push_str("// Do not edit by hand.\n\n");

    out.push_str("#[allow(clippy::approx_constant)]\n");
    out.push_str("pub const ZONE_LINES: &[ZoneLine] = &[\n");
    for z in &entries {
        out.push_str(&format!(
            "    ZoneLine {{ line_id: {}, from_zone: {}, from_pos: [{}f32, {}f32, {}f32], to_zone: {}, to_pos: [{}f32, {}f32, {}f32], scale_x: {}f32, scale_z: {}f32, rotation: {}f32 }},\n",
            z.line_id,
            z.from_zone,
            z.from_pos[0], z.from_pos[2], z.from_pos[1],
            z.to_zone,
            z.to_pos[0], z.to_pos[2], z.to_pos[1],
            z.scale_x, z.scale_z, z.rotation,
        ));
    }
    out.push_str("];\n\n");

    out.push_str("/// `(from_zone, start, end)` triples — one per distinct `from_zone`,\n");
    out.push_str("/// where `ZONE_LINES[start..end]` are that zone's outbound lines.\n");
    out.push_str("pub const ZONE_LINE_INDEX: &[(u16, u32, u32)] = &[\n");
    for (zone, start, end) in &index {
        out.push_str(&format!("    ({zone}, {start}, {end}),\n"));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("zonelines_table.rs"), &out)?;
    check_scrape_count(
        "zone-lines",
        LSB_ZONES_DATA_DIR,
        entries.len(),
        floor::ZONE_LINE,
    )?;
    check_scrape_count(
        "zone-line from_zones",
        LSB_ZONES_DATA_DIR,
        index.len(),
        floor::FROM_ZONE,
    )?;

    Ok(())
}

#[derive(Debug)]
struct ParsedLine {
    line_id: u32,
    from_zone: u16,
    from_pos: [f32; 3],
    to_zone: u16,
    to_pos: [f32; 3],
    scale_x: f32,
    scale_z: f32,
    rotation: f32,
}

/// The `zonelines:` map of every data/zones/<zone>/zone.yaml. A line is keyed
/// by its four-character client tag, which LSB packs little-endian into the
/// u32 the c2s 0x05E RectID carries
/// (vendor/server/src/map/data/datasets/zones/settings/dataset.cpp
/// packZoneLineId); `at` is x, y, z and an optional facing in radians
/// (vendor/server/src/map/data/shared_types/position.h
/// toPositionFacingRadians).
fn parse_zonelines(zone_ids: &HashMap<String, u16>) -> Result<Vec<ParsedLine>> {
    let mut out = Vec::new();
    for (zone_key, path) in zone_data_files(LSB_ZONES_DATA_DIR)? {
        let from_zone = *zone_ids.get(&zone_key).with_context(|| {
            format!(
                "{}: `{zone_key}` is not in {LSB_ZONE_ENUM_YAML}",
                path.display()
            )
        })?;
        let src =
            fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        let root = parse_yaml(&src).with_context(|| format!("parsing {}", path.display()))?;
        let Some(lines) = root.get("zonelines").and_then(Yaml::as_map) else {
            continue;
        };
        for (tag, line) in lines {
            let context = || format!("{}: zone line `{tag}`", path.display());
            let tag_bytes: [u8; 4] = tag
                .as_bytes()
                .try_into()
                .map_err(|_| anyhow::anyhow!("{}: is not four characters", context()))?;
            let line_id = u32::from_le_bytes(tag_bytes);
            let from = line.list::<f32>("from")?.with_context(context)?;
            let to: String = line.field("to")?.with_context(context)?;
            let to_zone = *zone_ids
                .get(&to)
                .with_context(|| format!("{}: `{to}` is not in {LSB_ZONE_ENUM_YAML}", context()))?;
            let at = line.list::<f32>("at")?.with_context(context)?;
            let scale = line.list::<f32>("scale")?.with_context(context)?;
            if from.len() != 3 || !(3..=4).contains(&at.len()) || scale.len() != 2 {
                bail!(
                    "{}: expected from[3], at[3|4], scale[2], got {}, {}, {}",
                    context(),
                    from.len(),
                    at.len(),
                    scale.len()
                );
            }
            out.push(ParsedLine {
                line_id,
                from_zone,
                from_pos: [from[0], from[1], from[2]],
                to_zone,
                to_pos: [at[0], at[1], at[2]],
                scale_x: scale[0],
                scale_z: scale[1],
                rotation: at.get(3).copied().unwrap_or(0.0),
            });
        }
    }
    if out.is_empty() {
        bail!("parsed zero zone lines under {LSB_ZONES_DATA_DIR}");
    }
    Ok(out)
}
